apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  project-id: acm-demo-2022
  cluster-name: demo-us-east4
  location: us-east4
  sync-repo: https://github.com/karlkfi/acm-examples-platform/
