apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  network-name: demo
  region: us-east4
  prefix: us-east4-
  ip-cidr-range: 10.2.0.0/16
  source-subnetwork-ip-ranges-to-nat: LIST_OF_SUBNETWORKS
