apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: /setters
  name: setters
  annotations:
    config.kubernetes.io/local-config: "true"
data:
  project-id: acm-demo-2022
  cluster-name: demo-us-west4
  location: us-west4
  master-ip-range: 10.254.0.16/28
  network-ref: projects/acm-demo-2022/global/networks/demo
  subnet-ref: projects/acm-demo-2022/regions/us-west4/subnetworks/us-west4-demo-subnetwork
  pods-range-name: pods
  services-range-name: services
  security-group: gke-security-groups@environblueprint.joonix.net
